# Generated by Django 5.0.1 on 2026-03-26 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0003_alter_bill_invoice_number_alter_bill_qty_total_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialYearClosureLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('client_count', models.PositiveIntegerField(default=0)),
                ('invoice_count', models.PositiveIntegerField(default=0)),
                ('payment_count', models.PositiveIntegerField(default=0)),
                ('opening_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('closing_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('backup_path', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='SUCCESS', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_year_closures', to=settings.AUTH_USER_MODEL)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closure_logs', to='Software.financialyear')),
                ('next_financial_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_from_closures', to='Software.financialyear')),
            ],
        ),
    ]
