# Generated by Django 5.0.1 on 2026-03-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0004_financialyearclosurelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(default='Gurukrupa Enterprise', max_length=200)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=12, null=True)),
                ('gstin', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('alternate_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='firm/')),
                ('bank_name', models.CharField(blank=True, max_length=120, null=True)),
                ('account_name', models.CharField(blank=True, max_length=120, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('rtgs_code', models.CharField(blank=True, max_length=30, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=120, null=True)),
                ('invoice_footer', models.TextField(blank=True, null=True)),
                ('invoice_terms', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
