# Generated by Django 5.0.1 on 2026-03-29 10:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0005_firmsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmsettings',
            name='cgst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.50'), max_digits=6),
        ),
        migrations.AddField(
            model_name='firmsettings',
            name='igst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='firmsettings',
            name='sgst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.50'), max_digits=6),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
