# Generated by Django 5.0.1 on 2026-03-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0006_firmsettings_cgst_rate_firmsettings_igst_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('TX', 'Taxable'), ('NT', 'Non-taxable')], max_length=2, unique=True)),
                ('prefix', models.CharField(max_length=2)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
