# Generated by Django 5.0.1 on 2026-03-29 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0007_invoicesequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='financial_year',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='financial_year',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='financial_year',
        ),
        migrations.DeleteModel(
            name='ClientYearBalance',
        ),
        migrations.DeleteModel(
            name='FinancialYearSequence',
        ),
        migrations.DeleteModel(
            name='FinancialYear',
        ),
        migrations.DeleteModel(
            name='FinancialYearClosureLog',
        ),
    ]
