# Generated by Django 5.0.1 on 2026-03-29 11:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0008_remove_financialyear_closed_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='description',
        ),
        migrations.AlterField(
            model_name='bill',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
