# Generated by Django 5.0.1 on 2026-03-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0009_remove_bill_description_alter_bill_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmsettings',
            name='show_invoice_delete_button',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='is_taxable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='invoicesequence',
            name='invoice_type',
            field=models.CharField(choices=[('TX', 'Taxable')], max_length=2, unique=True),
        ),
    ]
