# Generated by Django 5.0.1 on 2026-03-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0010_firmsettings_show_invoice_delete_button_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmsettings',
            name='show_payment_delete_button',
            field=models.BooleanField(default=True),
        ),
    ]
