# Generated by Django 5.0.1 on 2026-03-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0011_firmsettings_show_payment_delete_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmsettings',
            name='show_client_delete_button',
            field=models.BooleanField(default=True),
        ),
    ]
