# Generated by Django 5.0.1 on 2026-04-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Software", "0012_firmsettings_show_client_delete_button"),
    ]

    operations = [
        migrations.AddField(
            model_name="firmsettings",
            name="third_contact_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="firmsettings",
            name="invoice_template",
            field=models.CharField(
                choices=[("classic", "Classic"), ("invoice1", "Invoice 1")],
                default="classic",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="hsn_code",
            field=models.CharField(blank=True, default="6205", max_length=20, null=True),
        ),
    ]
