# Generated by Django 6.0.3 on 2026-04-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0013_firmsettings_third_contact_number_and_invoice_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmsettings',
            name='show_size_delete_button',
            field=models.BooleanField(default=True),
        ),
    ]
