# Generated by Django 6.0.3 on 2026-04-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0014_firmsettings_show_size_delete_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmsettings',
            name='show_product_delete_button',
            field=models.BooleanField(default=True),
        ),
    ]
